<?php

namespace Roman\ComponentApi\Dto\Response;

/**
 * @method setAED`
 * @method setAFN
 * @method setALL
 * @method setAMD
 * @method setANG
 * @method setAOA
 * @method setARS
 * @method setAUD
 * @method setAWG 
 * @method setAZN 
 * @method setBAM 
 * @method setBBD 
 * @method setBDT 
 * @method setBGN 
 * @method setBHD 
 * @method setBIF 
 * @method setBMD 
 * @method setBND 
 * @method setBOB 
 * @method setBRL 
 * @method setBSD 
 * @method setBTC 
 * @method setBTN 
 * @method setBWP 
 * @method setBYN 
 * @method setBZD 
 * @method setCAD 
 * @method setCDF 
 * @method setCHF 
 * @method setCLF 
 * @method setCLP 
 * @method setCNH 
 * @method setCNY 
 * @method setCOP 
 * @method setCRC 
 * @method setCUC 
 * @method setCUP 
 * @method setCVE 
 * @method setCZK 
 * @method setDJF 
 * @method setDKK 
 * @method setDOP 
 * @method setDZD 
 * @method setEGP 
 * @method setERN 
 * @method setETB 
 * @method setEUR 
 * @method setFJD 
 * @method setFKP 
 * @method setGBP 
 * @method setGEL 
 * @method setGGP 
 * @method setGHS 
 * @method setGIP 
 * @method setGMD 
 * @method setGNF 
 * @method setGTQ 
 * @method setGYD 
 * @method setHKD 
 * @method setHNL 
 * @method setHRK 
 * @method setHTG 
 * @method setHUF
 * @method setIDR
 * @method setILS
 * @method setIMP
 * @method setINR
 * @method setIQD
 * @method setIRR
 * @method setISK
 * @method setJEP
 * @method setJMD
 * @method setJOD
 * @method setJPY
 * @method setKES
 * @method setKGS
 * @method setKHR
 * @method setKMF
 * @method setKPW
 * @method setKRW
 * @method setKWD
 * @method setKYD
 * @method setKZT
 * @method setLAK
 * @method setLBP
 * @method setLKR
 * @method setLRD
 * @method setLSL
 * @method setLYD
 * @method setMAD
 * @method setMDL
 * @method setMGA
 * @method setMKD
 * @method setMMK 
 * @method setMNT 
 * @method setMOP
 * @method setMRU
 * @method setMUR
 * @method setMVR
 * @method setMWK
 * @method setMXN
 * @method setMYR
 * @method setMZN
 * @method setNAD
 * @method setNGN
 * @method setNIO
 * @method setNOK
 * @method setNPR
 * @method setNZD
 * @method setOMR
 * @method setPAB
 * @method setPEN
 * @method setPGK
 * @method setPHP
 * @method setPKR
 * @method setPLN
 * @method setPYG
 * @method setQAR
 * @method setRON
 * @method setRSD
 * @method setRUB
 * @method setRWF
 * @method setSAR
 * @method setSBD
 * @method setSCR
 * @method setSDG
 * @method setSEK
 * @method setSGD
 * @method setSHP
 * @method setSLL
 * @method setSOS
 * @method setSRD
 * @method setSSP
 * @method setSTD
 * @method setSTN
 * @method setSVC
 * @method setSYP
 * @method setSZL
 * @method setTHB
 * @method setTJS
 * @method setTMT
 * @method setTND
 * @method setTOP
 * @method setTRY
 * @method setTTD
 * @method setTWD
 * @method setTZS
 * @method setUAH
 * @method setUGX
 * @method setUSD
 * @method setUYU
 * @method setUZS
 * @medhod setVES
 * @medhod setVND
 * @medhod setVUV
 * @medhod setWST
 * @medhod setXAF
 * @medhod setXAG
 * @medhod setXAU
 * @medhod setXCD
 * @medhod setXDR
 * @medhod setXOF
 * @medhod setXPD
 * @medhod setXPF
 * @method setXPT
 * @method setYER
 * @method setZAR
 * @method setZMW
 * @method setZWL
 *
 * @method getAED
 * @method getAFN
 * @method getALL
 * @method getAMD
 * @method getANG
 * @method getAOA
 * @method getARS
 * @method getAUD
 * @method getAWG
 * @method getAZN
 * @method getBAM
 * @method getBBD
 * @method getBDT
 * @method getBGN
 * @method getBHD
 * @method getBIF
 * @method getBMD
 * @method getBND
 * @method getBOB
 * @method getBRL
 * @method getBSD
 * @method getBTC
 * @method getBTN
 * @method getBWP
 * @method getBYN
 * @method getBZD
 * @method getCAD
 * @method getCDF
 * @method getCHF
 * @method getCLF
 * @method getCLP
 * @method getCNH
 * @method getCNY
 * @method getCOP
 * @method getCRC
 * @method getCUC
 * @method getCUP
 * @method getCVE
 * @method getCZK
 * @method getDJF
 * @method getDKK
 * @method getDOP
 * @method getDZD
 * @method getEGP
 * @method getERN
 * @method getETB
 * @method getEUR
 * @method getFJD
 * @method getFKP
 * @method getGBP
 * @method getGEL
 * @method getGGP
 * @method getGHS
 * @method getGIP
 * @method getGMD
 * @method getGNF
 * @method getGTQ
 * @method getGYD
 * @method getHKD
 * @method getHNL
 * @method getHRK
 * @method getHTG
 * @method getHUF
 * @method getIDR
 * @method getILS
 * @method getIMP
 * @method getINR
 * @method getIQD
 * @method getIRR
 * @method getISK
 * @method getJEP
 * @method getJMD
 * @method getJOD
 * @method getJPY
 * @method getKES
 * @method getKGS
 * @method getKHR
 * @method getKMF
 * @method getKPW
 * @method getKRW
 * @method getKWD
 * @method getKYD
 * @method getKZT
 * @method getLAK
 * @method getLBP
 * @method getLKR
 * @method getLRD
 * @method getLSL
 * @method getLYD
 * @method getMAD
 * @method getMDL
 * @method getMGA
 * @method getMKD
 * @method getMMK
 * @method getMNT
 * @method getMOP
 * @method getMRU
 * @method getMUR
 * @method getMVR
 * @method getMWK
 * @method getMXN
 * @method getMYR
 * @method getMZN
 * @method getNAD
 * @method getNGN
 * @method getNIO
 * @method getNOK
 * @method getNPR
 * @method getNZD
 * @method getOMR
 * @method getPAB
 * @method getPEN
 * @method getPGK
 * @method getPHP
 * @method getPKR
 * @method getPLN
 * @method getPYG
 * @method getQAR
 * @method getRON
 * @method getRSD
 * @method getRUB
 * @method getRWF
 * @method getSAR
 * @method getSBD
 * @method getSCR
 * @method getSDG
 * @method getSEK
 * @method getSGD
 * @method getSHP
 * @method getSLL
 * @method getSOS
 * @method getSRD
 * @method getSSP
 * @method getSTD
 * @method getSTN
 * @method getSVC
 * @method getSYP
 * @method getSZL
 * @method getTHB
 * @method getTJS
 * @method getTMT
 * @method getTND
 * @method getTOP
 * @method getTRY
 * @method getTTD
 * @method getTWD
 * @method getTZS
 * @method getUAH
 * @method getUGX
 * @method getUSD
 * @method getUYU
 * @method getUZS
 * @medhod getVES
 * @medhod getVND
 * @medhod getVUV
 * @medhod getWST
 * @medhod getXAF
 * @medhod getXAG
 * @medhod getXAU
 * @medhod getXCD
 * @medhod getXDR
 * @medhod getXOF
 * @medhod getXPD
 * @medhod getXPF
 * @method getXPT
 * @method getYER
 * @method getZAR
 * @method getZMW
 * @method getZWL
 */
class RatesDto
{
    private array $data = [];

    /**
     * Generate set and get methods
     *
     * @param string $name
     * @param array $arguments
     * @return $this|mixed
     */
    public function __call(string $name, array $arguments) {
        if (str_starts_with($name, 'get')) {
            return $this->data[strtoupper(substr($name, 3))];
        } elseif (str_starts_with($name, 'set')) {
            $this->data[strtoupper(substr($name, 3))] = reset($arguments);
        }
        
        return $this;
    }

    /**
     * Set all data to dto
     *
     * @param array $data
     * @return void
     */
    public function setData(array $data): void
    {
        $this->data = $data;
    }
}